<?php

declare(strict_types=1);

namespace ProductResearch\AI\Schema;

use NeuronAI\StructuredOutput\SchemaProperty;
use NeuronAI\StructuredOutput\Validation\Rules\NotBlank;

/**
 * Single strategic recommendation generated by the AI agent.
 */
final class Recommendation
{
    #[SchemaProperty(description: 'Short recommendation title', required: true)]
    #[NotBlank]
    public string $title = '';

    #[SchemaProperty(description: 'Detailed explanation of the recommendation', required: true)]
    #[NotBlank]
    public string $description = '';

    #[SchemaProperty(description: 'Priority level: high, medium, or low', required: true)]
    #[NotBlank]
    public string $priority = 'medium';

    /**
     * Convert to array for JSON storage.
     *
     * @return array<string, string>
     */
    public function toArray(): array
    {
        return [
            'title'       => $this->title,
            'description' => $this->description,
            'priority'    => $this->priority,
        ];
    }
}
